apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-result
  namespace: workshop-day1-solutions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-result
  template:
    metadata:
      labels:
        app: voting-result
        version: v1
    spec:
      hostAliases:
       - ip: "127.0.0.1"
         hostnames:
          - "result"
          - "db"
          - "worker"
      containers:
       - name: db
         image: postgres:9.4
         volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: db-data
       - name: result
         image: dockersamples/examplevotingapp_result:before
         ports:
          - containerPort: 80 
       - name: worker
         image: dockersamples/examplevotingapp_worker
      volumes:
       - name: db-data
         emptyDir: {}
