apiVersion: apps/v1

# Note that this is a Deployment resource, but that the spec only 
# includes the desired replica count and pod template. No deployment
# options are included. This Deployment reosurce will use the defaults.
kind: Deployment
metadata:
  name: voter
  namespace: workshop-day1-solutions
spec:
  # The described pods are stateful and only route votes to the 
  # pod-local redis instance. Running multiple replicas would 
  # create a federated set with no linkage.
  replicas: 1
  selector:
    matchLabels:
      app: voter
  template:
    metadata:
      labels:
        app: voter
        version: v1
    spec:
      # This is a nice little hack that will tell the applications
      # in this pod to look to localhost when resolving  the redis
      # or vote names (instead of doing a full DNS lookup).
      hostAliases:
       - ip: "127.0.0.1"
         hostnames:
          - "vote"
          - "redis"
      containers:
       - name: vote
         image: dockersamples/examplevotingapp_vote:before
         ports:
          - containerPort: 80   # purely informational
       - name: redis
         image: redis:alpine
         ports:
          - containerPort: 6379 # purely informational
