apiVersion: v1
kind: Service
metadata:
  name: results-svc
  namespace: workshop-day1-solutions
spec:
  type: NodePort
  selector:
    app: voting-result
    version: v1
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-result
  namespace: workshop-day1-solutions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-result
  template:
    metadata:
      labels:
        app: voting-result
        version: v1
    spec:
      containers:
       - name: result
         image: dockersamples/examplevotingapp_result:after
         ports:
          - containerPort: 80
