apiVersion: v1
kind: ConfigMap
metadata:
  name: hw-config
  namespace: workshop-day2-solutions
data:
        username: Jessica
        password: HasAWeakPassword
        endpoint: http://localhost:8080/login
