apiVersion: v1
kind: ConfigMap
metadata:
  name: not-secret-config
  namespace: workshop-day2-solutions
data:
        username: Jeff
        password: TeachesThisClass
        endpoint: http://localhost:8080/login
