apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
    version: v1
  ports:
    - protocol: TCP
      port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres
    version: v1
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: voter-svc
spec:
  type: NodePort
  selector:
    app: voter
    version: v2
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: results-svc
spec:
  type: NodePort
  selector:
    app: voting-result
    version: v2
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001

