apiVersion: v1
kind: Service
metadata:
  name: voter-svc
  namespace: workshop-day2-solutions
spec:
  type: NodePort
  selector:
    app: voter
    version: v1
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voter
  namespace: workshop-day2-solutions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voter
  template:
    metadata:
      labels:
        app: voter
        version: v1
    spec:
      hostAliases:
       - ip: "127.0.0.1"
         hostnames:
          - "vote"
      containers:
       - name: vote
         image: dockersamples/examplevotingapp_vote:after
         ports:
          - containerPort: 80
